import type { DetectedConfig } from "../utils/detect"

export function generateDrizzleSchema(config: DetectedConfig): string {
    const lines: string[] = []

    lines.push(`// ▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱`)
    lines.push(`// Generated by @arraf-auth/cli`)
    lines.push(`// Do not edit this file manually`)
    lines.push(`// Copy these tables into your database schema file`)
    lines.push(`// Re-run: npx arraf-auth generate to update`)
    lines.push(`// ▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱`)
    lines.push(``)

    lines.push(`import {`)
    lines.push(`  pgTable,`)
    lines.push(`  text,`)
    lines.push(`  boolean,`)
    lines.push(`  timestamp,`)
    lines.push(`  integer,`)
    lines.push(`  uniqueIndex,`)
    lines.push(`  index,`)

    const verificationTypes = buildVerificationTypes(config)
    if (verificationTypes.length > 0) {
        lines.push(`  pgEnum,`)
    }

    lines.push(`} from "drizzle-orm/pg-core"`)
    lines.push(``)

    if (verificationTypes.length > 0) {
        lines.push(`export const verificationTypeEnum = pgEnum("verification_type", [`)
        verificationTypes.forEach((t) => lines.push(`  "${t}",`))
        lines.push(`])`)
        lines.push(``)
    }

    lines.push(`export const users = pgTable("users", {`)
    lines.push(`  id:            text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),`)
    lines.push(`  email:         text("email").unique(),`)
    lines.push(`  phone:         text("phone").unique(),`)
    lines.push(`  name:          text("name"),`)
    lines.push(`  emailVerified: boolean("email_verified").notNull().default(false),`)
    lines.push(`  phoneVerified: boolean("phone_verified").notNull().default(false),`)
    lines.push(`  image:         text("image"),`)
    lines.push(`  createdAt:     timestamp("created_at").notNull().defaultNow(),`)
    lines.push(`  updatedAt:     timestamp("updated_at").notNull().defaultNow(),`)

    // if (config.plugins.includes("twoFactor")) {
    //     lines.push(`  // Added by twoFactor plugin`)
    //     lines.push(`  twoFactorEnabled: boolean("two_factor_enabled").notNull().default(false),`)
    //     lines.push(`  twoFactorSecret:  text("two_factor_secret"),`)
    // }

    lines.push(`})`)
    lines.push(``)

    lines.push(`export const sessions = pgTable("sessions", {`)
    lines.push(`  id:        text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),`)
    lines.push(`  userId:    text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),`)
    lines.push(`  token:     text("token").notNull().unique(),`)
    lines.push(`  expiresAt: timestamp("expires_at").notNull(),`)
    lines.push(`  ipAddress: text("ip_address"),`)
    lines.push(`  userAgent: text("user_agent"),`)
    lines.push(`  createdAt: timestamp("created_at").notNull().defaultNow(),`)
    lines.push(`}, (t) => ({`)
    lines.push(`  userIdx:  index("sessions_user_idx").on(t.userId),`)
    lines.push(`  tokenIdx: index("sessions_token_idx").on(t.token),`)
    lines.push(`}))`)
    lines.push(``)

    lines.push(`export const accounts = pgTable("accounts", {`)
    lines.push(`  id:                   text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),`)
    lines.push(`  userId:               text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),`)
    lines.push(`  providerId:           text("provider_id").notNull(),`)
    lines.push(`  accountId:            text("account_id").notNull(),`)
    lines.push(`  accessToken:          text("access_token"),`)
    lines.push(`  refreshToken:         text("refresh_token"),`)
    lines.push(`  accessTokenExpiresAt: timestamp("access_token_expires_at"),`)
    lines.push(`  createdAt:            timestamp("created_at").notNull().defaultNow(),`)
    lines.push(`}, (t) => ({`)
    lines.push(`  providerAccountIdx: uniqueIndex("accounts_provider_account_idx").on(t.providerId, t.accountId),`)
    lines.push(`  userIdx:            index("accounts_user_idx").on(t.userId),`)
    lines.push(`}))`)
    lines.push(``)

    if (verificationTypes.length > 0) {
        lines.push(`export const verifications = pgTable("verifications", {`)
        lines.push(`  id:         text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),`)
        lines.push(`  identifier: text("identifier").notNull(),`)
        lines.push(`  token:      text("token").notNull(),`)
        lines.push(`  type:       verificationTypeEnum("type").notNull(),`)
        lines.push(`  expiresAt:  timestamp("expires_at").notNull(),`)
        lines.push(`  attempts:   integer("attempts").notNull().default(0),`)
        lines.push(`  createdAt:  timestamp("created_at").notNull().defaultNow(),`)
        lines.push(`}, (t) => ({`)
        lines.push(`  identifierTypeIdx: uniqueIndex("verifications_identifier_type_idx").on(t.identifier, t.type),`)
        lines.push(`  identifierIdx:     index("verifications_identifier_idx").on(t.identifier),`)
        lines.push(`}))`)
        lines.push(``)
    }

    // if (config.plugins.includes("twoFactor")) {
    //     lines.push(`// Added by twoFactor plugin`)
    //     lines.push(`export const twoFactorBackupCodes = pgTable("two_factor_backup_codes", {`)
    //     lines.push(`  id:        text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),`)
    //     lines.push(`  userId:    text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),`)
    //     lines.push(`  code:      text("code").notNull(),`)
    //     lines.push(`  used:      boolean("used").notNull().default(false),`)
    //     lines.push(`  createdAt: timestamp("created_at").notNull().defaultNow(),`)
    //     lines.push(`}, (t) => ({`)
    //     lines.push(`  userIdx: index("two_factor_user_idx").on(t.userId),`)
    //     lines.push(`}))`)
    //     lines.push(``)
    // }

    lines.push(`// Inferred types`)
    lines.push(`export type UserRecord         = typeof users.$inferSelect`)
    lines.push(`export type SessionRecord      = typeof sessions.$inferSelect`)
    lines.push(`export type AccountRecord      = typeof accounts.$inferSelect`)

    if (verificationTypes.length > 0) {
        lines.push(`export type VerificationRecord = typeof verifications.$inferSelect`)
    }

    return lines.join("\n")
}

function buildVerificationTypes(config: DetectedConfig): string[] {
    const types: string[] = []

    if (config.features.phoneOtp) types.push("phone_otp")
    if (config.features.emailVerification) types.push("email_otp", "email_verification")
    if (config.features.forgotPassword) types.push("forgot_password_email", "forgot_password_phone")
    // if (config.plugins.includes("twoFactor")) types.push("totp_setup")
    // if (config.plugins.includes("magicLink")) types.push("magic_link")

    return types
}