import type { DetectedConfig } from "../utils/detect"

export function generatePrismaSchema(config: DetectedConfig): string {
    const lines: string[] = []

    lines.push(`// ▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱`)
    lines.push(`// Generated by @arraf-auth/cli`)
    lines.push(`// Do not edit this file manually`)
    lines.push(`// Copy these tables into your database schema file`)
    lines.push(`// Re-run: npx arraf-auth generate to update`)
    lines.push(`// ▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱▰▱`)
    lines.push(``)
    lines.push(`generator client {`)
    lines.push(`  provider = "prisma-client-js"`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`datasource db {`)
    lines.push(`  provider = "postgresql"`)
    lines.push(`  url      = env("DATABASE_URL")`)
    lines.push(`  // You can change provider to: "mysql", "sqlite", "sqlserver"`)
    lines.push(`}`)
    lines.push(``)

    const verificationTypes: string[] = []

    if (config.features.phoneOtp) {
        verificationTypes.push(`  phone_otp`)
    }
    if (config.features.emailVerification) {
        verificationTypes.push(`  email_otp`)
        verificationTypes.push(`  email_verification`)
    }
    if (config.features.forgotPassword) {
        verificationTypes.push(`  forgot_password_email`)
        verificationTypes.push(`  forgot_password_phone`)
    }

    // if (config.plugins.includes("twoFactor")) {
    //     verificationTypes.push(`  totp_setup`)
    // }
    // if (config.plugins.includes("magicLink")) {
    //     verificationTypes.push(`  magic_link`)
    // }

    if (verificationTypes.length > 0) {
        lines.push(`enum VerificationType {`)
        lines.push(...verificationTypes)
        lines.push(`}`)
        lines.push(``)
    }

    lines.push(`model User {`)
    lines.push(`  id            String    @id @default(cuid())`)
    lines.push(`  email         String?   @unique`)
    lines.push(`  phone         String?   @unique`)
    lines.push(`  name          String?`)
    lines.push(`  emailVerified Boolean   @default(false)`)
    lines.push(`  phoneVerified Boolean   @default(false)`)
    lines.push(`  image         String?`)
    lines.push(`  createdAt     DateTime  @default(now())`)
    lines.push(`  updatedAt     DateTime  @updatedAt`)
    lines.push(``)
    lines.push(`  sessions      Session[]`)
    lines.push(`  accounts      Account[]`)

    // if (config.plugins.includes("twoFactor")) {
    //     lines.push(`  twoFactorEnabled Boolean @default(false)`)
    //     lines.push(`  twoFactorSecret  String?`)
    // }

    lines.push(``)
    lines.push(`  @@map("users")`)
    lines.push(`}`)
    lines.push(``)

    lines.push(`model Session {`)
    lines.push(`  id        String   @id @default(cuid())`)
    lines.push(`  userId    String`)
    lines.push(`  token     String   @unique`)
    lines.push(`  expiresAt DateTime`)
    lines.push(`  ipAddress String?`)
    lines.push(`  userAgent String?`)
    lines.push(`  createdAt DateTime @default(now())`)
    lines.push(``)
    lines.push(`  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)`)
    lines.push(``)
    lines.push(`  @@index([userId])`)
    lines.push(`  @@index([token])`)
    lines.push(`  @@map("sessions")`)
    lines.push(`}`)
    lines.push(``)

    lines.push(`model Account {`)
    lines.push(`  id                   String    @id @default(cuid())`)
    lines.push(`  userId               String`)
    lines.push(`  providerId           String`)
    lines.push(`  accountId            String`)
    lines.push(`  accessToken          String?`)
    lines.push(`  refreshToken         String?`)
    lines.push(`  accessTokenExpiresAt DateTime?`)
    lines.push(`  createdAt            DateTime  @default(now())`)
    lines.push(``)
    lines.push(`  user                 User      @relation(fields: [userId], references: [id], onDelete: Cascade)`)
    lines.push(``)
    lines.push(`  @@unique([providerId, accountId])`)
    lines.push(`  @@index([userId])`)
    lines.push(`  @@map("accounts")`)
    lines.push(`}`)
    lines.push(``)

    if (verificationTypes.length > 0) {
        lines.push(`model Verification {`)
        lines.push(`  id         String           @id @default(cuid())`)
        lines.push(`  identifier String`)
        lines.push(`  token      String`)
        lines.push(`  type       VerificationType`)
        lines.push(`  expiresAt  DateTime`)
        lines.push(`  attempts   Int              @default(0)`)
        lines.push(`  createdAt  DateTime         @default(now())`)
        lines.push(``)
        lines.push(`  @@unique([identifier, type])`)
        lines.push(`  @@index([identifier])`)
        lines.push(`  @@map("verifications")`)
        lines.push(`}`)
        lines.push(``)
    }

    // if (config.plugins.includes("twoFactor")) {
    //     lines.push(`// Added by twoFactor plugin`)
    //     lines.push(`model TwoFactorBackupCode {`)
    //     lines.push(`  id        String   @id @default(cuid())`)
    //     lines.push(`  userId    String`)
    //     lines.push(`  code      String`)
    //     lines.push(`  used      Boolean  @default(false)`)
    //     lines.push(`  createdAt DateTime @default(now())`)
    //     lines.push(``)
    //     lines.push(`  @@index([userId])`)
    //     lines.push(`  @@map("two_factor_backup_codes")`)
    //     lines.push(`}`)
    //     lines.push(``)
    // }

    return lines.join("\n")
}