packages:
  - packages/core
  - packages/adapters/*
  - packages/providers/*
  - packages/integrations/*
  - packages/cli
  - apps/*

onlyBuiltDependencies:
  - prisma
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
